;;; init-thing-edit.el --- Emacs Configuration. -*- lexical-binding: t -*-

;;; Commentary:

;;; Code:

(require 'thing-edit)
(defvar my/thing-edit-map (make-sparse-keymap)
  "Keybinding for `thing-edit'")
;; Copy.
(define-key my/thing-edit-map (kbd "w") 'thing-copy-word)
(define-key my/thing-edit-map (kbd "s") 'thing-copy-symbol)
(define-key my/thing-edit-map (kbd "m") 'thing-copy-email)
(define-key my/thing-edit-map (kbd "f") 'thing-copy-filename)
(define-key my/thing-edit-map (kbd "u") 'thing-copy-url)
(define-key my/thing-edit-map (kbd "x") 'thing-copy-sexp)
(define-key my/thing-edit-map (kbd "t") 'thing-copy-page)
(define-key my/thing-edit-map (kbd "v") 'thing-copy-sentence)
;;(define-key my/thing-edit-map (kbd "g") 'thing-copy-block)
(define-key my/thing-edit-map (kbd "o") 'thing-copy-whitespace)
(define-key my/thing-edit-map (kbd "i") 'thing-copy-list)
(define-key my/thing-edit-map (kbd "c") 'thing-copy-comment)
(define-key my/thing-edit-map (kbd "h") 'thing-copy-defun)
(define-key my/thing-edit-map (kbd "p") 'thing-copy-parentheses)
(define-key my/thing-edit-map (kbd "l") 'thing-copy-region-or-line)
(define-key my/thing-edit-map (kbd "a") 'thing-copy-to-line-beginning)
(define-key my/thing-edit-map (kbd "e") 'thing-copy-to-line-end)
;; Cut.
(define-key my/thing-edit-map (kbd "SPC w") 'thing-cut-word)
(define-key my/thing-edit-map (kbd "SPC s") 'thing-cut-symbol)
(define-key my/thing-edit-map (kbd "SPC m") 'thing-cut-email)
(define-key my/thing-edit-map (kbd "SPC f") 'thing-cut-filename)
(define-key my/thing-edit-map (kbd "SPC u") 'thing-cut-url)
(define-key my/thing-edit-map (kbd "SPC x") 'thing-cut-sexp)
(define-key my/thing-edit-map (kbd "SPC t") 'thing-cut-page)
(define-key my/thing-edit-map (kbd "SPC v") 'thing-cut-sentence)
;;(define-key my/thing-edit-map (kbd "SPC g") 'thing-cut-block)
(define-key my/thing-edit-map (kbd "SPC o") 'thing-cut-whitespace)
(define-key my/thing-edit-map (kbd "SPC i") 'thing-cut-list)
(define-key my/thing-edit-map (kbd "SPC c") 'thing-cut-comment)
(define-key my/thing-edit-map (kbd "SPC h") 'thing-cut-defun)
(define-key my/thing-edit-map (kbd "SPC l") 'thing-cut-region-or-line)
(define-key my/thing-edit-map (kbd "SPC p") 'thing-cut-parentheses)
(define-key my/thing-edit-map (kbd "SPC a") 'thing-cut-to-line-beginning)
(define-key my/thing-edit-map (kbd "SPC e") 'thing-cut-to-line-end)
;; Replace
(define-key my/thing-edit-map (kbd "W") 'thing-replace-word)
(define-key my/thing-edit-map (kbd "S") 'thing-replace-symbol)
(define-key my/thing-edit-map (kbd "M") 'thing-replace-email)
(define-key my/thing-edit-map (kbd "F") 'thing-replace-filename)
(define-key my/thing-edit-map (kbd "U") 'thing-replace-url)
(define-key my/thing-edit-map (kbd "X") 'thing-replace-sexp)
(define-key my/thing-edit-map (kbd "T") 'thing-replace-page)
(define-key my/thing-edit-map (kbd "V") 'thing-replace-sentence)
;;(define-key my/thing-edit-map (kbd "G") 'thing-replace-block)
(define-key my/thing-edit-map (kbd "O") 'thing-replace-whitespace)
(define-key my/thing-edit-map (kbd "I") 'thing-replace-list)
(define-key my/thing-edit-map (kbd "C") 'thing-replace-comment)
(define-key my/thing-edit-map (kbd "H") 'thing-replace-defun)
(define-key my/thing-edit-map (kbd "P") 'thing-replace-parentheses)
(define-key my/thing-edit-map (kbd "L") 'thing-replace-region-or-line)
(define-key my/thing-edit-map (kbd "A") 'thing-paste-to-line-beginning)
(define-key my/thing-edit-map (kbd "E") 'thing-paste-to-line-end)

(global-set-key (kbd "M-h") my/thing-edit-map)


(require 'avy-thing-edit)
(defvar my/avy-thing-edit-map (make-sparse-keymap)
  "Keybinding for `thing-edit'")
;; Copy.
(define-key my/avy-thing-edit-map (kbd "w") 'avy-thing-paste-word)
(define-key my/avy-thing-edit-map (kbd "s") 'avy-thing-paste-symbol)
(define-key my/avy-thing-edit-map (kbd "m") 'avy-thing-paste-email)
(define-key my/avy-thing-edit-map (kbd "f") 'avy-thing-paste-filename)
(define-key my/avy-thing-edit-map (kbd "u") 'avy-thing-paste-url)
(define-key my/avy-thing-edit-map (kbd "x") 'avy-thing-paste-sexp)
(define-key my/avy-thing-edit-map (kbd "t") 'avy-thing-paste-page)
(define-key my/avy-thing-edit-map (kbd "v") 'avy-thing-paste-sentence)
;;(define-key my/avy-thing-edit-map (kbd "g") 'avy-thing-paste-block)
(define-key my/avy-thing-edit-map (kbd "g") 'avy-thing-paste-region)
(define-key my/avy-thing-edit-map (kbd "o") 'avy-thing-paste-whitespace)
(define-key my/avy-thing-edit-map (kbd "i") 'avy-thing-paste-list)
(define-key my/avy-thing-edit-map (kbd "c") 'avy-thing-paste-comment)
(define-key my/avy-thing-edit-map (kbd "h") 'avy-thing-paste-defun)
(define-key my/avy-thing-edit-map (kbd "p") 'avy-thing-paste-parentheses)
(define-key my/avy-thing-edit-map (kbd "l") 'avy-thing-paste-region-or-line)
(define-key my/avy-thing-edit-map (kbd "a") 'avy-thing-paste-to-line-beginning)
(define-key my/avy-thing-edit-map (kbd "e") 'avy-thing-paste-to-line-end)
;; Cut.
(define-key my/avy-thing-edit-map (kbd "SPC w") 'avy-thing-cut-word)
(define-key my/avy-thing-edit-map (kbd "SPC s") 'avy-thing-cut-symbol)
(define-key my/avy-thing-edit-map (kbd "SPC m") 'avy-thing-cut-email)
(define-key my/avy-thing-edit-map (kbd "SPC f") 'avy-thing-cut-filename)
(define-key my/avy-thing-edit-map (kbd "SPC u") 'avy-thing-cut-url)
(define-key my/avy-thing-edit-map (kbd "SPC x") 'avy-thing-cut-sexp)
(define-key my/avy-thing-edit-map (kbd "SPC t") 'avy-thing-cut-page)
(define-key my/avy-thing-edit-map (kbd "SPC v") 'avy-thing-cut-sentence)
;;(define-key my/avy-thing-edit-map (kbd "SPC g") 'avy-thing-cut-block)
(define-key my/avy-thing-edit-map (kbd "SPC o") 'avy-thing-cut-whitespace)
(define-key my/avy-thing-edit-map (kbd "SPC i") 'avy-thing-cut-list)
(define-key my/avy-thing-edit-map (kbd "SPC c") 'avy-thing-cut-comment)
(define-key my/avy-thing-edit-map (kbd "SPC h") 'avy-thing-cut-defun)
(define-key my/avy-thing-edit-map (kbd "SPC p") 'avy-thing-cut-parentheses)
(define-key my/avy-thing-edit-map (kbd "SPC l") 'avy-thing-cut-region-or-line)
(define-key my/avy-thing-edit-map (kbd "SPC a") 'avy-thing-cut-to-line-beginning)
(define-key my/avy-thing-edit-map (kbd "SPC e") 'avy-thing-cut-to-line-end)
;; Replace
(define-key my/avy-thing-edit-map (kbd "W") 'avy-thing-replace-word)
(define-key my/avy-thing-edit-map (kbd "S") 'avy-thing-replace-symbol)
(define-key my/avy-thing-edit-map (kbd "M") 'avy-thing-replace-email)
(define-key my/avy-thing-edit-map (kbd "F") 'avy-thing-replace-filename)
(define-key my/avy-thing-edit-map (kbd "U") 'avy-thing-replace-url)
(define-key my/avy-thing-edit-map (kbd "X") 'avy-thing-replace-sexp)
(define-key my/avy-thing-edit-map (kbd "T") 'avy-thing-replace-page)
(define-key my/avy-thing-edit-map (kbd "V") 'avy-thing-replace-sentence)
;;(define-key my/avy-thing-edit-map (kbd "G") 'avy-thing-replace-block)
(define-key my/avy-thing-edit-map (kbd "O") 'avy-thing-replace-whitespace)
(define-key my/avy-thing-edit-map (kbd "I") 'avy-thing-replace-list)
(define-key my/avy-thing-edit-map (kbd "C") 'avy-thing-replace-comment)
(define-key my/avy-thing-edit-map (kbd "H") 'avy-thing-replace-defun)
(define-key my/avy-thing-edit-map (kbd "P") 'avy-thing-replace-parentheses)
(define-key my/avy-thing-edit-map (kbd "L") 'avy-thing-replace-region-or-line)
(define-key my/avy-thing-edit-map (kbd "A") 'avy-thing-paste-to-line-beginning)
(define-key my/avy-thing-edit-map (kbd "E") 'avy-thing-paste-to-line-end)

(global-set-key (kbd "M-'") my/avy-thing-edit-map)

(provide 'init-thing-edit)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-thing-edit.el ends here
